name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
    
      - name: Login using Service Principal
        run: |
          az login --service-principal -u 50b13126-3623-4f02-b5de-ecd6577ce08c -p rzB8Q~lkF9w3w02xRZv9.yHkyn6prLkuGNnIvaMm --tenant 62e3ed0a-e36b-449c-a4c5-9a7fa5b20d71

      - name: Verify Login
        run: |
          az account show


    
